doc: Added documentation 'README.md' and 'README.zh_CN.
linuxdeepin/dde-kwin pull request #352
Opened 2022-10-10 08:38 UTC by axylp

Added documentation 'README.md' and 'README.zh_CN.

2022-10-12 05:52 UTC, xzl01 requested changes
readme内容与项目无关联，无参考性

2022-10-12 06:13 UTC, BLumia requested changes
即便要直接复制现有其它项目的资料，也应当调整成符合自身项目实际情况的描述。自述文档应当能让刚刚接触项目的人能够对项目实际有所了解，并实际可以参照使用。

现在这份 README 的内容和项目完全对不上号...

2022-10-20 07:57 UTC, hitong602 submitted a review, later dismissed

2022-10-20 08:56 UTC, axylp commented
/merge

2022-10-21 02:07 UTC, BLumia approved these changes

2022-10-21 02:12 UTC, merged